# Render Configuration for AI Quiz App
# This file defines the services to be deployed on Render

# Backend Service (Flask)
services:
  - type: web
    name: ai-quiz-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --worker-connections=1000 --timeout 120 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: FLASK_APP
        value: "run.py"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
        sync: false
